### ISSUE TITLE
Glyphfriend on .aspx page

### ISSUE THREAD

**Issue by billhoelzer** [Rionmonster/Glyphfriend#40]
I installed the Glyphfriend in Visual Studio 2015. The intellisense does not work on an .aspx page but it works fine on an .html page. Is there something else I need to get this to work on an .aspx page?

**Comment by Rionmonster** [comment]
> The intellisense does not work on an .aspx page but it works fine on an .html page.

This is intentional and unfortunately going to be the answer. 

It comes down to editor that is used for Web Forms being significantly different than that of the one that handles HTML content, namely that the Web Forms editor is not at all extensible. After reading your issue, I made several attempts to attempt to implement the behavior, but it's simply a matter of there not being anything to hook into.
