### ISSUE TITLE
Glyphfriend and Dark Theme

### ISSUE THREAD

**Issue by david-hollifield** [Rionmonster/Glyphfriend#43]
Is there an option somewhere that supports VStudio's dark theme mode? My icons end up looking like this and it's pretty hard to read. Using the R# version, BTW. Nice extension.

![image](https://cloud.githubusercontent.com/assets/686784/14292433/0d32c230-fb36-11e5-9800-74d27ff81add.png)

**Comment by Rionmonster** [comment]
Hi @david-hollifield,

Thanks for reaching out and for your comments about the extension, they are appreciated. 

With regards to your issue, this problem is actually isolated to the Resharper version of the extension, which was developed by @Huntk23 and I believe is a [known issue](https://github.com/Huntk23/ResharperGlyphfriend/issues/1) as the Dark theme appears to work as expected in Visual Studio : 

![image](https://cloud.githubusercontent.com/assets/1325081/14296457/df3b2188-fb3f-11e5-8865-b2d34fc53777.png)

I'll certainly check out the issue within the Resharper version to see if I can pinpoint something or make a PR when I have some time to fix it, but hopefully it should be resolved soon.

**Comment by david-hollifield** [comment]
Ah, thank you. I thought the R# version was part of this project. My bad. I'll check over there. Sorry for the confusion.

**Comment by Huntk23** [comment]
Hi @david-hollifield,

Just an update from my end. I have been rewriting the Resharper Extension of this but waiting for their 2016.1 release before I deploy anything. (Should be in the next week or so)

My other problem is I can only develop the Resharper Extension at work since I don't have a personal home copy to work with. Work has been swamped at the moment but things are easing up.
