### ISSUE TITLE
Does it work with WPF/XAML?

### ISSUE THREAD

**Issue by tongbong** [rionmonster/Glyphfriend#46]
Hi,

great stuff, I am looking for that kind of tool for XAML.
Is it supported?

Cheers,
F.

**Comment by Rionmonster** [comment]
Hi @tongbong, 

I honestly haven't tested it at all on any XAML projects, but I'll do a check of this for the next release. Glyphfriend currently only explicitly targets HTML-based files (and Markdown), so I'm not sure it would work in its current state for those, but it might be doable.

**Comment by tongbong** [comment]
Thanks for the quick answer. Looking forward to have some feedback about that and if the task is doable and does not require heavy work I would gladly offer my help.

**Comment by Rionmonster** [comment]
XAML isn't currently supported in Glyphfriend as the event listeners to register the GlyphCompletion events only detect HTML-based content as seen in the [HtmlTextViewListener class](https://github.com/Rionmonster/Glyphfriend/blob/master/Helpers/HtmlTextViewListener.cs):  

```
[Export(typeof(IVsTextViewCreationListener))]
[ContentType("htmlx")]
[TextViewRole(PredefinedTextViewRoles.Document)]
class HtmlTextViewListener : IVsTextViewCreationListener
{
      // Code omitted for brevity
}
```

With that being said, I don't think that XAML could be out of the realm of possibility if this is truly a need. Could you provide some examples of how you might use it and for what type of attributes? It's been a *long* time since I have written any XAML, so you might have a better use-case than I could think of. Doing this would also assume that you would actually include the necessary `CSS` files within your Project for detection purposes.

**Comment by tongbong** [comment]
The use case is :
- given a set of icons in an IconDictionary.xaml file in the current project,
- given the extra property Icon on class FrameworkElement (done by extension),

then the intellisense should come very handy when writing: 
`<Button Icon="{StaticResource MyIcon"></Button>`
in order to code complete the value of Icon tag with {StaticResource MyIcon} after selecting the icon from the intellisense menu.

Based on the markdown sample, I managed to adapt it for xaml. But I guess the hard thing to achieve is to read dictionary as the source of images.

**Comment by rionmonster** [comment]
Closing this issue for now as it seems to be a bit beyond the scope of the project, which is designed to handle dealing with specific sets in certain libraries (e.g. Font Awesome, Material Design, etc.)

While it is probably do-able, this extension may not be the best place for it.
