### ISSUE TITLE
Office imageMso support?

### ISSUE THREAD

**Issue by nbelyh** [rionmonster/Glyphfriend#57]
Dear Rion,

First, thank you so much for a great tool!

As an idea/suggestion - would you think it could make sense to add support for office ribbon icons (so called "imageMso" images) to help people who design office extensions using XML. This has been an issue for a while already, and these are really hard to find. Check out this tool for example:

https://imagemso.codeplex.com/
https://msdn.microsoft.com/en-us/library/dd953682.aspx
http://www.excelguru.ca/blog/2007/05/05/identifying-your-imagemso-excel-word-powerpoint/

It shows the images, but it would be great if autocomplete can be done. I could assist with incorporating these images. Please note, in case there are A LOT of them (more than 8.000) so keeping them as they are now (as file set in a folder) seem to be problematic in this case. I have tried to implement that in my fork, please check the screenshot of what i'm talking about:

![image](https://cloud.githubusercontent.com/assets/528366/17193918/8c9424ec-5455-11e6-9523-dd3bed2b2019.png)

Anyways, your thoughts are most welcome. Do you think such a feature worth adding, or it could be better to go for a separate project for such thing?

Kind regards,
Nikolay.

**Comment by nbelyh** [comment]
Created new project. The office idMso database seems to be too large (>8000 images) and a bit too specific to include it for everyone. Also added support for XML autocompletion (idMso/insertAfterMso/insertBeforeMso)

https://github.com/nbelyh/IdMsoAutocomplete

https://visualstudiogallery.msdn.microsoft.com/7be17bc0-c682-40df-aaa0-6f2e8e8fdb14

**Comment by rionmonster** [comment]
Hi @nbelyh,

Sorry for the delayed response, things have been a bit crazy on my end. Yes, as you mentioned this extension may have not been the best place for this as this primarily focuses on the font-based glyph libraries (the markdown implementation itself was a bit of a stretch and simply was done due to the sheer volume of e-mail requests).

I'm glad to hear that you were able to get everything working as a separate extension.
