### ISSUE TITLE
After Install VS Still Says Missing

### ISSUE THREAD

**Issue by spottedmahn** [rionmonster/Glyphfriend#84]
![image](https://cloud.githubusercontent.com/assets/14079228/23183007/833cf7c4-f848-11e6-97d0-11cc88942dec.png)

I've tried installing via the "View Extensions" above and I don't get any errors but the message never goes away even after closing and re-opening.

I've also tried installing via the vsix file from the marketplace and that install says successful but it still doesn't work.

[VSIXInstaller_7b599b27-791d-4b3d-95b6-b87566074304.zip](https://github.com/rionmonster/Glyphfriend/files/791391/VSIXInstaller_7b599b27-791d-4b3d-95b6-b87566074304.zip)

VS 2015 Community Edition

Thanks!

**Comment by rionmonster** [comment]
Have you tried completely un-installing Glyphfriend and then re-installing it?

If it's being suggested by the View Extensions dialog then there may be an actual issue, as I don't believe that version is still a working / active version of Glyphfriend. Can you elaborate on what other extensions that you have installed so that I can see if any _might_ be interfering with this?

I appreciate you reporting this, and I hope that I can get it resolved (or at least figure out what might be causing it).

**Comment by rionmonster** [comment]
Just an update,

After speaking with Mads, I've determined that this issue occurred when the previous version of Glyphfriend was refactored into the two newer separate extensions (one targeting VS2015 and the other targeting VS2017). During this time the project identifier for Glyphfriend was changed, and Visual Studio used a previous value to recommend users to Glyphfriend. Since the value changed, the extension was left in a limbo by only recommending users to essentially install the version they already had, perpetually.

An upcoming release in the next few days should reset the ID value to it's original state and allow things to pick back up as expected.

Thanks again for reporting this.
