### ISSUE TITLE
Visual Studio MPF 15.0 Dependency

### ISSUE THREAD

**Issue by afernandes** [rionmonster/Glyphfriend#87]
Error trying to update in Visual Studio 2015.

![image](https://cloud.githubusercontent.com/assets/867631/23457736/d9995e86-fe57-11e6-8922-01c864c2c80b.png)

**Comment by rionmonster** [comment]
Wow.

I can't believe that I missed this, it turns out a recent change to fix how Visual Studio managed updating Glyphfriend (and chose which version of the extension to use) was targeting the 2017 edition of the extension instead of the 2015 version.

I pushed out an update this morning that should resolve this unnecessary dependency. Thank you so much for reporting the issue, which should now be resolved. Let me know if you continue to encounter the error.

**Comment by afernandes** [comment]
I was able to update successfully!
Thank you very much! :)

**Comment by Rogue899** [comment]
is still happening with the 2019 version
