### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by reader-man** [rionmonster/Glyphfriend#91]
Hi,
 Thanks or the great tool you have.

I was wondering if VS 2017 support is on the way?

Regards.

**Comment by rionmonster** [comment]
Glyphfriend has been supported in Visual Studio 2017 since an early RC release. One important thing to note is that it _is_ a separate extension called [Glyphfriend 2017](https://marketplace.visualstudio.com/items?itemName=RionWilliams.Glyphfriend2017).

You can download it from the Visual Studio Marketplace at the link just provided or directly within Visual Studio in the Extensions and Updates area.

**Comment by reader-man** [comment]
Thank you very much on this very helpful tool.

Regards.

**Comment by reader-man** [comment]
Sorry, just another note.
The VS 2017 suggested ur tool, and thats how i knew it, but it gave link to the 2015 one, so if there is away you can help in directing VS 2017, to use the one that is made for it, it would be better.

Regards.
